CREATE TABLE TBL_EVENT_EMOTIONS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    event_id NUMBER,
    day DATE DEFAULT SYSDATE,
    empty NUMBER DEFAULT 0,
    sadness NUMBER DEFAULT 0,
    enthusiasm NUMBER DEFAULT 0,
    neutral NUMBER DEFAULT 0,
    worry NUMBER DEFAULT 0,
    surprise NUMBER DEFAULT 0,
    love NUMBER DEFAULT 0,
    fun NUMBER DEFAULT 0,
    hate NUMBER DEFAULT 0,
    happiness NUMBER DEFAULT 0,
    boredom NUMBER DEFAULT 0,
    relief NUMBER DEFAULT 0,
    anger NUMBER DEFAULT 0
);

CREATE OR REPLACE PROCEDURE INCREASE_EVENT_EMOTION(
    p_event_id IN NUMBER,
    p_emotion IN VARCHAR2
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM TBL_EVENT_EMOTIONS
    WHERE event_id = p_event_id
      AND TRUNC(day) = TRUNC(SYSDATE);

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'UPDATE TBL_EVENT_EMOTIONS SET ' || p_emotion || ' = ' || p_emotion || ' + 1 WHERE event_id = :event_id AND TRUNC(day) = TRUNC(SYSDATE)'
        USING p_event_id;
    ELSE
        EXECUTE IMMEDIATE 'INSERT INTO TBL_EVENT_EMOTIONS (event_id, ' || p_emotion || ') VALUES (:event_id, 1)'
        USING p_event_id;
    END IF;
END;
